"""Added phone number for user

Revision ID: 268102d710a6
Revises: f5a4c3eaa54c
Create Date: 2026-03-14 19:14:08.881490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268102d710a6'
down_revision = 'f5a4c3eaa54c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
