"""Fixec relationship and added cascade

Revision ID: 458ff656ce16
Revises: 268102d710a6
Create Date: 2026-03-15 19:40:56.909276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '458ff656ce16'
down_revision = '268102d710a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
