"""Added more fields

Revision ID: f5a4c3eaa54c
Revises: 5e2f79893ff5
Create Date: 2026-02-23 22:22:04.597789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a4c3eaa54c'
down_revision = '5e2f79893ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('age', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('vaccinated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelters', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('vaccinated')
        batch_op.drop_column('status')
        batch_op.drop_column('gender')
        batch_op.drop_column('size')
        batch_op.drop_column('age')
        batch_op.drop_column('breed')

    # ### end Alembic commands ###
